### ISSUE TITLE
UTF-8 Encoding Support

### ISSUE THREAD

**Issue by Digote** [ArchLeaders/MsbtToYaml#2]
Firstly, congratulations on the tool! I really like the .yaml format and was in need of a converter for any .msbt file. I'm excited to be able to edit the tags as well.

I'm currently running a test with the game Tokyo Mirage Sessions ♯FE, out of the 1048 files, only the Shop.msbt couldn't be converted. I've tested it in other languages and the same issue occurs.

Error:

MSBT to YAML [Version 1.0.0]
(c) 2024 ArchLeaders. MIT.

Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at MessageStudio.Formats.BinaryText.Structures.MsbtText.WriteUtf8(StringBuilder& sb)
   at MessageStudio.Formats.BinaryText.Structures.MsbtText.GetManaged()
   at MessageStudio.Formats.BinaryText.Msbt.FromImmutable(ImmutableMsbt& msbt, MsbtOptions options)
   at MessageStudio.Formats.BinaryText.Msbt.FromBinary(Span`1 buffer, MsbtOptions options)
   at Program.<Main>$(String[] args)
   
   
   
 Attached is the file.

[Shop.zip](https://github.com/ArchLeaders/MsbtToYaml/files/15044079/Shop.zip)

**Comment by ArchLeaders** [comment]
UTF8 MSBT files are not supported at the moment.

https://github.com/EPD-Libraries/MessageStudio/issues/1
